language: python

python:
  - "3.5"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mpich

install:
  - pip3 install -r requirements.txt
  - python3 setup.py install

script:
  - htcf-demux -h
